_str1 = input().split()
a = int(_str1[0])
b = int(_str1[1])
_str2 = input().split()
a2 = int(_str2[0])
b2 = int(_str2[1])
_str3 = input().split()
a3 = int(_str3[0])
b3 = int(_str3[1])

print(int(a-a3), int(b-b2))